node {
	def commit_id
	stage('Preparation') {
		checkout scm
		sh "git rev-parse --short HEAD > .git/commit-id"
		commit_id = readFile('.git/commit-id').trim()
	}
	stage('test') {
		nodejs(nodeJSInstallationName: 'nodejs') {
		    sh 'node -v'
		    sh 'npm -v'
			sh 'npm install --only=dev'
			//sh 'npm run test'
		}
	}
	stage('docker build/push') {
		docker.withRegistry('', '052d6a55-7fa3-49a6-8925-5bf2871fa151') {
			def app = docker.build("acruzr/service-web-app", '-f build/Dockerfile .').push()
		}
	}
}